# -*- coding: utf-8 -*-
"""rock-paper-scissors-game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/pratheeshsailor/5996c3f2d3a6ca1bcfd0d95f118a748a/rock-paper-scissors-game.ipynb
"""

import random

Player_A_Wins = 0
Player_B_Wins = 0

options = ["rock", "paper", "scissors"]

while True:
    Player_A = input("Type Rock/Paper/Scissors or Q to quit: ").lower()
    if Player_A == "q":
        break

    if Player_A not in options:
        continue

    random_number = random.randint(0, 2)
    # rock: 0, paper: 1, scissors: 2
    Player_B = options[random_number]
    print("Computer picked", computer_pick + ".")

    if Player_A == "rock" and Player_B == "scissors":
        print("You won!")
        user_wins += 1

    elif Player_A == "paper" and Player_B == "rock":
        print("You won!")
        user_wins += 1

    elif Player_A == "scissors" and Player_B == "paper":
        print("You won!")
        user_wins += 1

    else:
        print("You lost!")
        computer_wins += 1

print("You won", Player_A_Wins, "times.")
print("The Player_B won", Player_B_Wins, "times.")
print("Goodbye!")

